In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3])

In [9]:
mylist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mymatrix = np.array(mylist)

In [11]:
mymatrix.shape

(3, 3)

In [12]:
mynewmatrix = np.array(mylist)

In [13]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
type(0.0)

float

In [18]:
type(0.)

float

In [19]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones((5, 5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [24]:
[1, 1, 1, 1] + 100

TypeError: can only concatenate list (not "int") to list

In [25]:
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

In [26]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [27]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [28]:
len(np.linspace(0, 10, 20))

20

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(1)

array([0.27316914])

In [31]:
np.random.rand(4)

array([0.09423737, 0.65275732, 0.71853701, 0.60639628])

In [32]:
np.random.rand(5, 5)

array([[0.23266637, 0.2560292 , 0.97021462, 0.21159507, 0.46002597],
       [0.90108091, 0.74354429, 0.52744433, 0.23186714, 0.69586238],
       [0.28317905, 0.98385453, 0.29945843, 0.31867505, 0.85079697],
       [0.80808019, 0.89284429, 0.64347076, 0.80691496, 0.81337181],
       [0.10891789, 0.39603186, 0.75633789, 0.63703889, 0.96572694]])

In [34]:
np.random.randn(10)

array([-0.16381621, -0.25559397, -0.65835372, -0.41466182,  0.69369138,
        1.81759264,  1.47799492, -0.83094235, -0.41295382, -1.17522514])

In [35]:
# np.random.normal()

In [37]:
np.random.randint(1, 100, 10)

array([84, 98, 12, 63, 11, 97,  2, 63, 93, 80])

In [40]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [41]:
np.random.rand(4)

array([0.58120733, 0.14267862, 0.94591918, 0.33999059])

In [42]:
np.random.rand(4)

array([0.62043546, 0.45295964, 0.23976742, 0.03450459])

In [43]:
arr = np.arange(25)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr = np.random.randint(0, 50, 10)

In [46]:
ranarr

array([ 1, 42, 41, 20, 13, 19,  3, 19, 36, 23])

In [47]:
arr.shape

(25,)

In [48]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr

array([ 1, 42, 41, 20, 13, 19,  3, 19, 36, 23])

In [50]:
ranarr.max()

42

In [51]:
ranarr.min()

1

In [52]:
ranarr.argmax()

1

In [53]:
ranarr.argmin()

0

In [54]:
ranarr

array([ 1, 42, 41, 20, 13, 19,  3, 19, 36, 23])

In [55]:
ranarr.dtype

dtype('int64')