In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3])

In [9]:
mylist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
mymatrix = np.array(mylist)

In [12]:
mymatrix.shape

(3, 3)

In [13]:
mynewmatrix = np.array(mylist)

In [14]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
type(0.0)

float

In [20]:
type(0.)

float

In [21]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.ones((5, 5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [24]:
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [27]:
[1, 1, 1, 1] + 100

TypeError: can only concatenate list (not "int") to list

In [28]:
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

In [29]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [30]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [31]:
len(np.linspace(0, 10, 20))

20

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])