In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.12.1'

In [4]:
arr = np.array([1, 2, 3, 4, 5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

In [9]:
x = torch.from_numpy(arr)

In [10]:
type(x)

torch.Tensor

In [11]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [12]:
x

tensor([1, 2, 3, 4, 5])

In [13]:
x.dtype

torch.int64

In [14]:
arr2d = np.arange(0.0, 12.0)

In [15]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [18]:
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [19]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
x

tensor([1, 2, 3, 4, 5])

In [22]:
arr[0] = 99

In [23]:
arr

array([99,  2,  3,  4,  5])

In [24]:
x

tensor([99,  2,  3,  4,  5])

In [25]:
my_arr = np.arange(0, 10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_tensor = torch.tensor(my_arr)

In [27]:
my_other_tensor = torch.from_numpy(my_arr)

In [28]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_arr[0] = 9999

In [31]:
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [32]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [34]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])