In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.12.1'

In [4]:
arr = np.array([1, 2, 3, 4, 5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

In [8]:
x = torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [10]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [11]:
x

tensor([1, 2, 3, 4, 5])

In [12]:
x.dtype

torch.int64

In [13]:
arr2d = np.arange(0.0, 12.0)

In [14]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [15]:
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [16]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
x

tensor([1, 2, 3, 4, 5])

In [19]:
arr[0] = 99

In [20]:
arr

array([99,  2,  3,  4,  5])

In [21]:
x

tensor([99,  2,  3,  4,  5])

In [22]:
my_arr = np.arange(0, 10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_tensor = torch.tensor(my_arr)

In [24]:
my_other_tensor = torch.from_numpy(my_arr)

In [25]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_arr[0] = 9999

In [28]:
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [29]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [30]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
new_arr = np.array([1, 2, 3])

In [33]:
new_arr.dtype

dtype('int64')

In [34]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [36]:
my_tensor = torch.Tensor(new_arr)

In [37]:
my_tensor.dtype

torch.float32

In [39]:
torch.empty(4, 2)

tensor([[0.0000e+00, 3.8177e-05],
        [1.0842e-19, 3.8177e-05],
        [1.0842e-19, 3.8177e-05],
        [0.0000e+00, 4.7684e-06]])

In [41]:
torch.zeros(4, 3, dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [42]:
torch.zeros(4, 3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [43]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [44]:
torch.arange(0, 18, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [45]:
torch.arange(0, 18, 2).reshape(3, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [46]:
torch.linspace(0, 18, 12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [47]:
torch.linspace(0, 18, 12).reshape(3, 4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [48]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [49]:
my_tensor = torch.tensor([1, 2, 3])

In [50]:
my_tensor.dtype

torch.int64

In [51]:
my_tensor.type()

'torch.LongTensor'

In [52]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [53]:
my_tensor = my_tensor.type(torch.int32)

In [54]:
my_tensor.dtype

torch.int32

In [55]:
torch.rand(4, 3)

tensor([[0.8576, 0.1459, 0.9465],
        [0.7315, 0.3467, 0.3852],
        [0.0383, 0.7476, 0.4946],
        [0.0284, 0.1047, 0.3323]])

In [56]:
torch.randn(4, 3)

tensor([[ 0.1072,  0.8526,  0.1116],
        [-0.5690, -0.0524,  0.3841],
        [ 0.0797, -1.3162, -0.7361],
        [ 0.7812,  1.4686,  0.8592]])

In [57]:
torch.randint(low=0, high=10, size=(5, 5))

tensor([[1, 6, 1, 2, 0],
        [2, 1, 0, 0, 6],
        [9, 6, 7, 2, 5],
        [8, 9, 8, 6, 1],
        [7, 6, 4, 2, 1]])

In [58]:
torch.randint(low=0, high=11, size=(5, 5))

tensor([[ 3,  5,  5, 10,  5],
        [ 8,  4,  2,  1,  7],
        [ 1,  0,  4,  9,  9],
        [ 4,  0,  8,  6,  9],
        [ 8,  6,  3,  4,  6]])

In [59]:
x = torch.zeros(2, 5)

In [60]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [61]:
x.shape

torch.Size([2, 5])

In [62]:
torch.rand_like(x)

tensor([[0.0356, 0.5109, 0.6307, 0.5085, 0.3134],
        [0.4870, 0.4836, 0.3515, 0.4892, 0.4791]])

In [64]:
torch.randn_like(x)

tensor([[-0.8302, -1.3117,  2.3228,  1.3142, -1.4971],
        [-0.3103,  0.4359, -2.3824,  0.6779,  0.2725]])

In [65]:
torch.randint_like(x, low=0, high=11)

tensor([[5., 4., 5., 6., 3.],
        [4., 3., 5., 2., 9.]])

In [66]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [67]:
torch.rand(2, 3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [68]:
torch.rand(2, 3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])