In [2]:
import numpy as np
import torch

In [5]:
x = torch.arange(6).reshape(3, 2)

In [7]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
x[1, 1]

tensor(3)

In [9]:
type(x[1, 1])

torch.Tensor

In [10]:
x[:, 1]

tensor([1, 3, 5])

In [11]:
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [12]:
x = torch.arange(10)

In [13]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x = x.reshape(2, 5)

In [19]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
x = torch.arange(10)

In [21]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x.shape

torch.Size([10])

In [23]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
z = x.view(2, 5)

In [25]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
x[0] = 9999

In [27]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [28]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [29]:
x = torch.arange(10)

In [30]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x.shape

torch.Size([10])

In [32]:
# Infer what the 2nd dimension
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [33]:
x.view(-1, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [63]:
a = torch.tensor([1., 2., 3.])

In [64]:
b = torch.tensor([4., 5., 6.])

In [65]:
a

tensor([1., 2., 3.])

In [66]:
b

tensor([4., 5., 6.])

In [67]:
a.dtype

torch.float32

In [68]:
b.type

<function Tensor.type>

In [69]:
b.dtype

torch.float32

In [70]:
a + b

tensor([5., 7., 9.])

In [71]:
torch.add(a, b)

tensor([5., 7., 9.])

In [72]:
# a = a + b

a.mul(b)

tensor([ 4., 10., 18.])

In [73]:
a

tensor([1., 2., 3.])

In [74]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [61]:
a

tensor([ 4., 10., 18.])

In [62]:
a

tensor([ 4., 10., 18.])